message = input("what does it feel like outside ? ")
name = input("what is your name ? ")
age = input("how old are you ? ")
print()
print("so its nice outside: ")
print(message)
print("whats your name again ? ")
print(name)
print("how old did you say you were ? ")
print(age)
print("you sure dont look your age: ")
